apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: wg-nginx-test
    kubernetes.io/name: wg-nginx-test
  name: wg-nginx-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: wg-nginx-test
  type: ClusterIP
